// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JavaPackage.proto

package com.mylearn.netty.mygame;

public final class JavaPackage {
  private JavaPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes mEquipID = 1;
    /**
     * <code>required bytes mEquipID = 1;</code>
     */
    boolean hasMEquipID();
    /**
     * <code>required bytes mEquipID = 1;</code>
     */
    com.google.protobuf.ByteString getMEquipID();

    // required bytes mAnimationID = 2;
    /**
     * <code>required bytes mAnimationID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    boolean hasMAnimationID();
    /**
     * <code>required bytes mAnimationID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    com.google.protobuf.ByteString getMAnimationID();

    // required bytes mHP = 3;
    /**
     * <code>required bytes mHP = 3;</code>
     */
    boolean hasMHP();
    /**
     * <code>required bytes mHP = 3;</code>
     */
    com.google.protobuf.ByteString getMHP();

    // required int32 mPosx = 4;
    /**
     * <code>required int32 mPosx = 4;</code>
     */
    boolean hasMPosx();
    /**
     * <code>required int32 mPosx = 4;</code>
     */
    int getMPosx();

    // required int32 mPosy = 5;
    /**
     * <code>required int32 mPosy = 5;</code>
     */
    boolean hasMPosy();
    /**
     * <code>required int32 mPosy = 5;</code>
     */
    int getMPosy();

    // required int32 mPosz = 6;
    /**
     * <code>required int32 mPosz = 6;</code>
     */
    boolean hasMPosz();
    /**
     * <code>required int32 mPosz = 6;</code>
     */
    int getMPosz();

    // required int32 mRosx = 7;
    /**
     * <code>required int32 mRosx = 7;</code>
     */
    boolean hasMRosx();
    /**
     * <code>required int32 mRosx = 7;</code>
     */
    int getMRosx();

    // required int32 mRosy = 8;
    /**
     * <code>required int32 mRosy = 8;</code>
     */
    boolean hasMRosy();
    /**
     * <code>required int32 mRosy = 8;</code>
     */
    int getMRosy();

    // required int32 mRosz = 9;
    /**
     * <code>required int32 mRosz = 9;</code>
     */
    boolean hasMRosz();
    /**
     * <code>required int32 mRosz = 9;</code>
     */
    int getMRosz();
  }
  /**
   * Protobuf type {@code com.mylearn.netty.mygame.Test}
   */
  public static final class Test extends
      com.google.protobuf.GeneratedMessage
      implements TestOrBuilder {
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test defaultInstance;
    public static Test getDefaultInstance() {
      return defaultInstance;
    }

    public Test getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mEquipID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              mAnimationID_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              mHP_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mPosx_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mPosy_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              mPosz_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              mRosx_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              mRosy_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              mRosz_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mylearn.netty.mygame.JavaPackage.internal_static_com_mylearn_netty_mygame_Test_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mylearn.netty.mygame.JavaPackage.internal_static_com_mylearn_netty_mygame_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mylearn.netty.mygame.JavaPackage.Test.class, com.mylearn.netty.mygame.JavaPackage.Test.Builder.class);
    }

    public static com.google.protobuf.Parser<Test> PARSER =
        new com.google.protobuf.AbstractParser<Test>() {
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes mEquipID = 1;
    public static final int MEQUIPID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString mEquipID_;
    /**
     * <code>required bytes mEquipID = 1;</code>
     */
    public boolean hasMEquipID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes mEquipID = 1;</code>
     */
    public com.google.protobuf.ByteString getMEquipID() {
      return mEquipID_;
    }

    // required bytes mAnimationID = 2;
    public static final int MANIMATIONID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString mAnimationID_;
    /**
     * <code>required bytes mAnimationID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public boolean hasMAnimationID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes mAnimationID = 2;</code>
     *
     * <pre>
     * Unique ID number for this person.
     * </pre>
     */
    public com.google.protobuf.ByteString getMAnimationID() {
      return mAnimationID_;
    }

    // required bytes mHP = 3;
    public static final int MHP_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString mHP_;
    /**
     * <code>required bytes mHP = 3;</code>
     */
    public boolean hasMHP() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes mHP = 3;</code>
     */
    public com.google.protobuf.ByteString getMHP() {
      return mHP_;
    }

    // required int32 mPosx = 4;
    public static final int MPOSX_FIELD_NUMBER = 4;
    private int mPosx_;
    /**
     * <code>required int32 mPosx = 4;</code>
     */
    public boolean hasMPosx() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 mPosx = 4;</code>
     */
    public int getMPosx() {
      return mPosx_;
    }

    // required int32 mPosy = 5;
    public static final int MPOSY_FIELD_NUMBER = 5;
    private int mPosy_;
    /**
     * <code>required int32 mPosy = 5;</code>
     */
    public boolean hasMPosy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 mPosy = 5;</code>
     */
    public int getMPosy() {
      return mPosy_;
    }

    // required int32 mPosz = 6;
    public static final int MPOSZ_FIELD_NUMBER = 6;
    private int mPosz_;
    /**
     * <code>required int32 mPosz = 6;</code>
     */
    public boolean hasMPosz() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 mPosz = 6;</code>
     */
    public int getMPosz() {
      return mPosz_;
    }

    // required int32 mRosx = 7;
    public static final int MROSX_FIELD_NUMBER = 7;
    private int mRosx_;
    /**
     * <code>required int32 mRosx = 7;</code>
     */
    public boolean hasMRosx() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 mRosx = 7;</code>
     */
    public int getMRosx() {
      return mRosx_;
    }

    // required int32 mRosy = 8;
    public static final int MROSY_FIELD_NUMBER = 8;
    private int mRosy_;
    /**
     * <code>required int32 mRosy = 8;</code>
     */
    public boolean hasMRosy() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 mRosy = 8;</code>
     */
    public int getMRosy() {
      return mRosy_;
    }

    // required int32 mRosz = 9;
    public static final int MROSZ_FIELD_NUMBER = 9;
    private int mRosz_;
    /**
     * <code>required int32 mRosz = 9;</code>
     */
    public boolean hasMRosz() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 mRosz = 9;</code>
     */
    public int getMRosz() {
      return mRosz_;
    }

    private void initFields() {
      mEquipID_ = com.google.protobuf.ByteString.EMPTY;
      mAnimationID_ = com.google.protobuf.ByteString.EMPTY;
      mHP_ = com.google.protobuf.ByteString.EMPTY;
      mPosx_ = 0;
      mPosy_ = 0;
      mPosz_ = 0;
      mRosx_ = 0;
      mRosy_ = 0;
      mRosz_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMEquipID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMAnimationID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMHP()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMPosx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMPosy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMPosz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMRosx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMRosy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMRosz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, mEquipID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, mAnimationID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, mHP_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, mPosx_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, mPosy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, mPosz_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, mRosx_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, mRosy_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, mRosz_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, mEquipID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, mAnimationID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, mHP_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mPosx_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mPosy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, mPosz_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, mRosx_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, mRosy_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, mRosz_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mylearn.netty.mygame.JavaPackage.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mylearn.netty.mygame.JavaPackage.Test prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mylearn.netty.mygame.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mylearn.netty.mygame.JavaPackage.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mylearn.netty.mygame.JavaPackage.internal_static_com_mylearn_netty_mygame_Test_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mylearn.netty.mygame.JavaPackage.internal_static_com_mylearn_netty_mygame_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mylearn.netty.mygame.JavaPackage.Test.class, com.mylearn.netty.mygame.JavaPackage.Test.Builder.class);
      }

      // Construct using com.mylearn.netty.mygame.JavaPackage.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mEquipID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        mAnimationID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        mHP_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        mPosx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        mPosy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        mPosz_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        mRosx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        mRosy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        mRosz_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mylearn.netty.mygame.JavaPackage.internal_static_com_mylearn_netty_mygame_Test_descriptor;
      }

      public com.mylearn.netty.mygame.JavaPackage.Test getDefaultInstanceForType() {
        return com.mylearn.netty.mygame.JavaPackage.Test.getDefaultInstance();
      }

      public com.mylearn.netty.mygame.JavaPackage.Test build() {
        com.mylearn.netty.mygame.JavaPackage.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mylearn.netty.mygame.JavaPackage.Test buildPartial() {
        com.mylearn.netty.mygame.JavaPackage.Test result = new com.mylearn.netty.mygame.JavaPackage.Test(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mEquipID_ = mEquipID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mAnimationID_ = mAnimationID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mHP_ = mHP_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mPosx_ = mPosx_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mPosy_ = mPosy_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mPosz_ = mPosz_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.mRosx_ = mRosx_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.mRosy_ = mRosy_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.mRosz_ = mRosz_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mylearn.netty.mygame.JavaPackage.Test) {
          return mergeFrom((com.mylearn.netty.mygame.JavaPackage.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mylearn.netty.mygame.JavaPackage.Test other) {
        if (other == com.mylearn.netty.mygame.JavaPackage.Test.getDefaultInstance()) return this;
        if (other.hasMEquipID()) {
          setMEquipID(other.getMEquipID());
        }
        if (other.hasMAnimationID()) {
          setMAnimationID(other.getMAnimationID());
        }
        if (other.hasMHP()) {
          setMHP(other.getMHP());
        }
        if (other.hasMPosx()) {
          setMPosx(other.getMPosx());
        }
        if (other.hasMPosy()) {
          setMPosy(other.getMPosy());
        }
        if (other.hasMPosz()) {
          setMPosz(other.getMPosz());
        }
        if (other.hasMRosx()) {
          setMRosx(other.getMRosx());
        }
        if (other.hasMRosy()) {
          setMRosy(other.getMRosy());
        }
        if (other.hasMRosz()) {
          setMRosz(other.getMRosz());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMEquipID()) {
          
          return false;
        }
        if (!hasMAnimationID()) {
          
          return false;
        }
        if (!hasMHP()) {
          
          return false;
        }
        if (!hasMPosx()) {
          
          return false;
        }
        if (!hasMPosy()) {
          
          return false;
        }
        if (!hasMPosz()) {
          
          return false;
        }
        if (!hasMRosx()) {
          
          return false;
        }
        if (!hasMRosy()) {
          
          return false;
        }
        if (!hasMRosz()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mylearn.netty.mygame.JavaPackage.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mylearn.netty.mygame.JavaPackage.Test) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes mEquipID = 1;
      private com.google.protobuf.ByteString mEquipID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mEquipID = 1;</code>
       */
      public boolean hasMEquipID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes mEquipID = 1;</code>
       */
      public com.google.protobuf.ByteString getMEquipID() {
        return mEquipID_;
      }
      /**
       * <code>required bytes mEquipID = 1;</code>
       */
      public Builder setMEquipID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mEquipID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mEquipID = 1;</code>
       */
      public Builder clearMEquipID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mEquipID_ = getDefaultInstance().getMEquipID();
        onChanged();
        return this;
      }

      // required bytes mAnimationID = 2;
      private com.google.protobuf.ByteString mAnimationID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mAnimationID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public boolean hasMAnimationID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes mAnimationID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public com.google.protobuf.ByteString getMAnimationID() {
        return mAnimationID_;
      }
      /**
       * <code>required bytes mAnimationID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder setMAnimationID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mAnimationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mAnimationID = 2;</code>
       *
       * <pre>
       * Unique ID number for this person.
       * </pre>
       */
      public Builder clearMAnimationID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mAnimationID_ = getDefaultInstance().getMAnimationID();
        onChanged();
        return this;
      }

      // required bytes mHP = 3;
      private com.google.protobuf.ByteString mHP_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mHP = 3;</code>
       */
      public boolean hasMHP() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes mHP = 3;</code>
       */
      public com.google.protobuf.ByteString getMHP() {
        return mHP_;
      }
      /**
       * <code>required bytes mHP = 3;</code>
       */
      public Builder setMHP(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mHP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mHP = 3;</code>
       */
      public Builder clearMHP() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mHP_ = getDefaultInstance().getMHP();
        onChanged();
        return this;
      }

      // required int32 mPosx = 4;
      private int mPosx_ ;
      /**
       * <code>required int32 mPosx = 4;</code>
       */
      public boolean hasMPosx() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 mPosx = 4;</code>
       */
      public int getMPosx() {
        return mPosx_;
      }
      /**
       * <code>required int32 mPosx = 4;</code>
       */
      public Builder setMPosx(int value) {
        bitField0_ |= 0x00000008;
        mPosx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mPosx = 4;</code>
       */
      public Builder clearMPosx() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mPosx_ = 0;
        onChanged();
        return this;
      }

      // required int32 mPosy = 5;
      private int mPosy_ ;
      /**
       * <code>required int32 mPosy = 5;</code>
       */
      public boolean hasMPosy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 mPosy = 5;</code>
       */
      public int getMPosy() {
        return mPosy_;
      }
      /**
       * <code>required int32 mPosy = 5;</code>
       */
      public Builder setMPosy(int value) {
        bitField0_ |= 0x00000010;
        mPosy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mPosy = 5;</code>
       */
      public Builder clearMPosy() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mPosy_ = 0;
        onChanged();
        return this;
      }

      // required int32 mPosz = 6;
      private int mPosz_ ;
      /**
       * <code>required int32 mPosz = 6;</code>
       */
      public boolean hasMPosz() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 mPosz = 6;</code>
       */
      public int getMPosz() {
        return mPosz_;
      }
      /**
       * <code>required int32 mPosz = 6;</code>
       */
      public Builder setMPosz(int value) {
        bitField0_ |= 0x00000020;
        mPosz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mPosz = 6;</code>
       */
      public Builder clearMPosz() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mPosz_ = 0;
        onChanged();
        return this;
      }

      // required int32 mRosx = 7;
      private int mRosx_ ;
      /**
       * <code>required int32 mRosx = 7;</code>
       */
      public boolean hasMRosx() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 mRosx = 7;</code>
       */
      public int getMRosx() {
        return mRosx_;
      }
      /**
       * <code>required int32 mRosx = 7;</code>
       */
      public Builder setMRosx(int value) {
        bitField0_ |= 0x00000040;
        mRosx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mRosx = 7;</code>
       */
      public Builder clearMRosx() {
        bitField0_ = (bitField0_ & ~0x00000040);
        mRosx_ = 0;
        onChanged();
        return this;
      }

      // required int32 mRosy = 8;
      private int mRosy_ ;
      /**
       * <code>required int32 mRosy = 8;</code>
       */
      public boolean hasMRosy() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 mRosy = 8;</code>
       */
      public int getMRosy() {
        return mRosy_;
      }
      /**
       * <code>required int32 mRosy = 8;</code>
       */
      public Builder setMRosy(int value) {
        bitField0_ |= 0x00000080;
        mRosy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mRosy = 8;</code>
       */
      public Builder clearMRosy() {
        bitField0_ = (bitField0_ & ~0x00000080);
        mRosy_ = 0;
        onChanged();
        return this;
      }

      // required int32 mRosz = 9;
      private int mRosz_ ;
      /**
       * <code>required int32 mRosz = 9;</code>
       */
      public boolean hasMRosz() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 mRosz = 9;</code>
       */
      public int getMRosz() {
        return mRosz_;
      }
      /**
       * <code>required int32 mRosz = 9;</code>
       */
      public Builder setMRosz(int value) {
        bitField0_ |= 0x00000100;
        mRosz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mRosz = 9;</code>
       */
      public Builder clearMRosz() {
        bitField0_ = (bitField0_ & ~0x00000100);
        mRosz_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mylearn.netty.mygame.Test)
    }

    static {
      defaultInstance = new Test(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mylearn.netty.mygame.Test)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mylearn_netty_mygame_Test_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mylearn_netty_mygame_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021JavaPackage.proto\022\030com.mylearn.netty.m" +
      "ygame\"\225\001\n\004Test\022\020\n\010mEquipID\030\001 \002(\014\022\024\n\014mAni" +
      "mationID\030\002 \002(\014\022\013\n\003mHP\030\003 \002(\014\022\r\n\005mPosx\030\004 \002" +
      "(\005\022\r\n\005mPosy\030\005 \002(\005\022\r\n\005mPosz\030\006 \002(\005\022\r\n\005mRos" +
      "x\030\007 \002(\005\022\r\n\005mRosy\030\010 \002(\005\022\r\n\005mRosz\030\t \002(\005B\'\n" +
      "\030com.mylearn.netty.mygameB\013JavaPackage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mylearn_netty_mygame_Test_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mylearn_netty_mygame_Test_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mylearn_netty_mygame_Test_descriptor,
              new java.lang.String[] { "MEquipID", "MAnimationID", "MHP", "MPosx", "MPosy", "MPosz", "MRosx", "MRosy", "MRosz", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
